language: node_js
node_js:
    - node
cache:
    directories:
        - node_modules
install:
    - npm install
script:
    - npm run build
deploy:
    provider: pages
    github_token: $GITHUB_TOKEN
    skip_cleanup: true
    keep_history: false
    local_dir: build
    on:
        branch: master
